name: auto deploy

on:
  [push]

jobs:
  build: # job 1
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout # step 1 get source code
      uses: actions/checkout@v1
      with:
        submodules: true

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Cache node modules # step 2
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies # step 3
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install # install node modules dependencies

    # Deploy hexo blog website.
    - name: Deploy # step 4
      id: deploy
      uses: sma11black/hexo-action@v1.0.0
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
